In [ ]:
Q1.create an array of shape (3,3,3)and find the dimension,size of the array

In [2]:
import numpy as np

In [3]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [4]:
a.ndim

3

In [6]:
a.size

9

In [ ]:
Q2.create an identify array, add 100 to the array elements,and then divide it with 3.

In [6]:
 a = np.tri(6,6)

In [7]:
a

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
a+100

array([[101., 100., 100., 100., 100., 100.],
       [101., 101., 100., 100., 100., 100.],
       [101., 101., 101., 100., 100., 100.],
       [101., 101., 101., 101., 100., 100.],
       [101., 101., 101., 101., 101., 100.],
       [101., 101., 101., 101., 101., 101.]])

In [9]:
a

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
a/3

array([[0.33333333, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.33333333, 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.        ,
        0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333]])

In [ ]:
Q3.create an array and a matrix and show any three difference using puthon.

In [ ]:
Q4.create a random arary of int , of shape 5,6.find the max , mean ,std,var of that array.

In [9]:
from numpy import random  as rd

In [10]:
rd.rand(5,6)

array([[0.54739883, 0.82097038, 0.7972211 , 0.42250527, 0.13868445,
        0.34526646],
       [0.68015443, 0.2417373 , 0.46405843, 0.02936253, 0.59583004,
        0.73433383],
       [0.01883513, 0.6668773 , 0.97886119, 0.72862586, 0.47430398,
        0.11602073],
       [0.90112708, 0.12774768, 0.80492186, 0.24413561, 0.17376217,
        0.81529794],
       [0.01324202, 0.32844358, 0.13030632, 0.44820297, 0.97922172,
        0.79490768]])

In [11]:
a.max()

9

In [13]:
a.mean()

5.0

In [17]:
a.std()

2.581988897471611

In [16]:
np.std(a)

2.581988897471611

In [18]:
a.var()

6.666666666666667

In [20]:
np.var(a)

6.666666666666667

In [ ]:
Q5.using linspace creat an array betwwen 100 to 102,and that array should have 50 elements in it.

In [3]:
np.linspace(100,102,50)

array([100.        , 100.04081633, 100.08163265, 100.12244898,
       100.16326531, 100.20408163, 100.24489796, 100.28571429,
       100.32653061, 100.36734694, 100.40816327, 100.44897959,
       100.48979592, 100.53061224, 100.57142857, 100.6122449 ,
       100.65306122, 100.69387755, 100.73469388, 100.7755102 ,
       100.81632653, 100.85714286, 100.89795918, 100.93877551,
       100.97959184, 101.02040816, 101.06122449, 101.10204082,
       101.14285714, 101.18367347, 101.2244898 , 101.26530612,
       101.30612245, 101.34693878, 101.3877551 , 101.42857143,
       101.46938776, 101.51020408, 101.55102041, 101.59183673,
       101.63265306, 101.67346939, 101.71428571, 101.75510204,
       101.79591837, 101.83673469, 101.87755102, 101.91836735,
       101.95918367, 102.        ])

In [ ]:
Q6.what is the diffence between arange and range,show it using python code.

In [ ]:
np.arrange()

In [ ]:
Q7.create an array of 3,3, but the values of the array should be between 0to1.

In [5]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [ ]:
Q8.create an array of shape (3,4)the values in the array should be between 10 to 50 .
then filter out the values which are greater 20 but less than 50.

In [13]:
tom=np.array([[[[10,20,30],[40,50,22],[32,31,24],[12,34,45]]]])


In [14]:
tom

array([[[[10, 20, 30],
         [40, 50, 22],
         [32, 31, 24],
         [12, 34, 45]]]])

In [17]:
tom[tom>20],"greater"

(array([30, 40, 50, 22, 32, 31, 24, 34, 45]), 'greater')

In [18]:
tom[tom<50],"lower"

(array([10, 20, 30, 40, 22, 32, 31, 24, 12, 34, 45]), 'lower')

In [ ]:
Q9.using python prove that a.a-1 = identity array

In [ ]:
Q10.wap to label a number even or odd in the range of 100,400.provide each digit

In [2]:
l = [1,2,3,4,5,6,7]
n =len(l)
while n-1:
    a = int(input())
    for i in l:
        if i ==a:
            l.remove(a)
            print(l)
            n-=1

1
[2, 3, 4, 5, 6, 7]
2
[3, 4, 5, 6, 7]
3
[4, 5, 6, 7]
4
[5, 6, 7]
5
[6, 7]
6
[7]


In [7]:
import numpy as np

In [8]:
arr = np.array([1,2,3,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [9]:
for i in range(len(arr)):
    if arr[i]%2==0:
        arr[i]="even"
    else:
        arr[i]="odd"
print(arr)

ValueError: invalid literal for int() with base 10: 'odd'