In [ ]:
#array

In [1]:
import numpy as np

In [14]:
distance = [10,15,17,26]
time = [.30,.47,.55,1.20]
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time
speed
type(speed)

numpy.ndarray

In [1]:
import numpy as np 

In [17]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
a.ndim

1

In [19]:
a.shape

(3,)

In [20]:
a.dtype

dtype('int32')

In [21]:
a.size

3

In [3]:
states = np.array(["guj","maha","mp","up","ap","wb","or","uk","pun"])
states

array(['guj', 'maha', 'mp', 'up', 'ap', 'wb', 'or', 'uk', 'pun'],
      dtype='<U4')

In [4]:
states.size

9

In [5]:
states.ndim

1

In [6]:
states.shape

(9,)

In [8]:
states.dtype

dtype('<U4')

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a[1][1:,]

array([5, 6])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a[0:,0:1]

array([[1],
       [4],
       [7]])

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
basic operation in numpy ndarry

In [52]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
a+b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [54]:
b-a

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [55]:
a*b

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [56]:
a/b

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [57]:
a//b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [58]:
b%a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [60]:
b<50

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [61]:
b[b<50]

array([10, 20, 30, 40])

In [ ]:
create an array of two students getting marks in 5 subject . 
if the marks is less than 50 , print the value of those marks
from the array 

In [11]:
a = np.array({"subject":[" Hindi","English","Science","SSt","Maths"],"marks":[65,35,24,35,57]})
i = 50 
while i>0 :
    

array({'subject': [' Hindi', 'English', 'Science', 'SSt', 'Maths'], 'marks': [65, 35, 24, 35, 57]},
      dtype=object)

In [ ]:
def 

In [ ]:
def greet():
    names = input("names : ").split()
    for i in names :
        if "a" in i : 
            print("good morning :",i)
        else:
            print("hello",i)
greet()

In [ ]:
if l>0 and u>0 and d>0 and sp>0 and len(p)>=10:

In [29]:
c = np.array(["Subjects"["Hindi","English","Science","SSt","Maths",[32,22,25,46,13]:index ["golu","molu"]]])
c

SyntaxError: invalid syntax (Temp/ipykernel_2408/379344522.py, line 1)

In [9]:
subjects = np.array(["English","Hindi","Math","Science","Economics"])
subjects


array(['English', 'Hindi', 'Math', 'Science', 'Economics'], dtype='<U9')

In [ ]:
25 may

In [26]:
# logical an operation 

In [6]:
import numpy as np

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a[(a>14)|(a<20)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[(a>14)&(a==23)]

array([], dtype=int32)

In [11]:
for i in a :
    #print(i)
    for j in i :
        print(j)

1
2
3
4
5
6
7
8
9


In [12]:
#copy and view

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a1 = a
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a2 = a.view()
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a3 = a.copy()
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a3[1][1]=50

In [49]:
a3

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.asarray()

In [ ]:
np.array is important is it useful of all time.

In [ ]:
#univerasal Function 

In [53]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
from numpy import pi

In [61]:
np.sin(pi)

1.2246467991473532e-16

In [60]:
np.sin(2*pi)

-2.4492935982947064e-16

In [62]:
np.cos(pi)

-1.0

In [66]:
# floor and ceiling
print(np.floor(np.array([12.34,-9.45,16.23,10.02])))
np.ceil(np.array([12.34,-9.45,16.23,10.02]))

[ 12. -10.  16.  10.]


array([13., -9., 17., 11.])

In [67]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [68]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
# shape Manipulation 

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [72]:
a.resize(9,1)

In [73]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [74]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [79]:
# broadcasting

a+10

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [80]:
a*100

array([[100],
       [200],
       [300],
       [400],
       [500],
       [600],
       [700],
       [800],
       [900]])

In [81]:
a/2

array([[0.5],
       [1. ],
       [1.5],
       [2. ],
       [2.5],
       [3. ],
       [3.5],
       [4. ],
       [4.5]])

In [82]:
a**2

array([[ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36],
       [49],
       [64],
       [81]], dtype=int32)

In [89]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
#broadcasting:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a**2

array([[ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36],
       [49],
       [64],
       [81]], dtype=int32)

In [92]:
arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.trace(a)

1

In [95]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.trace(a2)

15

In [6]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.diag(a,k=0)

array([1, 5, 9])

In [9]:
np.diag(a,k=1)

array([2, 6])

In [10]:
np.diag(a,k=-1)

array([4, 8])

In [11]:
np.tri(5,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.tri(5,5,k=2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.tri(5,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [14]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [18]:
np.tril(a,-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [19]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [20]:
np.diagflat(a)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [21]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [22]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
np.arange(0.2,7.8,.33)

array([0.2 , 0.53, 0.86, 1.19, 1.52, 1.85, 2.18, 2.51, 2.84, 3.17, 3.5 ,
       3.83, 4.16, 4.49, 4.82, 5.15, 5.48, 5.81, 6.14, 6.47, 6.8 , 7.13,
       7.46, 7.79])

In [25]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [26]:
np.logspace(10,20,10)

array([1.00000000e+10, 1.29154967e+11, 1.66810054e+12, 2.15443469e+13,
       2.78255940e+14, 3.59381366e+15, 4.64158883e+16, 5.99484250e+17,
       7.74263683e+18, 1.00000000e+20])

In [ ]:
random number generation :

In [28]:
from numpy import random as rd

In [29]:
rd.rand(3,3)

array([[0.92894659, 0.02526677, 0.43891657],
       [0.50239616, 0.44921791, 0.69991904],
       [0.65420633, 0.83145695, 0.80074881]])

In [31]:
rd.randn(2,2)

array([[-0.80425661,  2.44021073],
       [-1.13624094, -0.35307458]])

In [ ]:
this upper question is important questions:

In [33]:
rd.randint(5,30,20)

array([10,  5, 20, 10, 27, 27, 13, 28, 24,  6,  6, 15, 21, 17, 22, 16, 14,
       28,  6, 11])

In [34]:
a = rd.randint(5,30,(3,3))

In [35]:
a

array([[29, 23, 25],
       [ 5,  5,  9],
       [19, 12, 20]])

In [36]:
a.max()

29

In [37]:
a.min()

5

In [41]:
np.median(a)

19.0

In [42]:
np.std(a)

8.366600265340756

In [43]:
np.var(a)

70.0