In [ ]:
Q1. State the CLT

Q2. We have Dataset like this  120,132,144,123,156,190,178,165,183.
Find the mean , median , std , var ,check if the distribution is normal.
                      
Q3.State what is a random variable and what is PDF , CDF and PMF.
Can we have CDF of Discrete variable 

Q4.What is the key difference between Covariance and Corelation ?

Q5. Compute the Spearman Corelation coefficient.

45
78
89
67
56
99
70
98
33
68
78 
45
90
70
66
91
88
56
100
80


Q6. pop mean  = 400
      Sample mean = 370
      Sample std  = 30
      C.I  = 95%
      N = 80

Q7. pop mean  = 33
       Sample mean = 30
       Sample std = 2.5
      Alpha = 0.10
      N = 8
Q8. 
Observed 
A
B
C
D
Owned 1 dog
60
50
30
20
Owned 2 dog
30
20
15
10

 Check for the degree of independence 



In [ ]:
Q1. State the CLT

In [ ]:
The CLT is a statistical theory that states that - if you take a sufficiently large sample size 
from a population with a finite level of variance, the mean of all samples from that population 
will be roughly equal to the population mean.

In [48]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib

In [ ]:
Q2. We have Dataset like this  120,132,144,123,156,190,178,165,183.
Find the mean , median , std , var ,check if the distribution is normal.

In [4]:
a = pd.Series([120,132,144,123,156,190,178,165,183])
a

0    120
1    132
2    144
3    123
4    156
5    190
6    178
7    165
8    183
dtype: int64

In [44]:
a.mean()

154.55555555555554

In [43]:
a.median()

156.0

In [42]:
a.std()

26.30642084696772

In [41]:
a.var()

692.0277777777777

In [45]:
a.skew()

-0.03322541177603332

In [46]:
a.kurt()

-1.6431069756967012

In [ ]:
Q3.State what is a random variable and what is PDF , CDF and PMF.
Can we have CDF of Discrete variable

In [ ]:
The PDF (defined for Continuous Random Variables) is given by taking the first derivate of CDF.
For discrete random variable that takes on discrete values, is it common to defined Probability Mass Function.

In [ ]:
Q4.What is the key difference between Covariance and Corelation ?

In [ ]:
The main difference between covariance and correlation is that covariance measures
the strength or weakness of the correlation between two or more sets of random variables. 
On the other hand, correlation means to serve as an extended form of covariance.

In [ ]:
Q5. Compute the Spearman Corelation coefficient.

In [50]:
a = pd.Series([45,78,89,67,56,99,70,98,33,68])
b = pd.Series([78,45,90,70,66,91,88,56,100,80]) 
print(a)
print(b)

0    45
1    78
2    89
3    67
4    56
5    99
6    70
7    98
8    33
9    68
dtype: int64
0     78
1     45
2     90
3     70
4     66
5     91
6     88
7     56
8    100
9     80
dtype: int64


In [51]:
a.corr(b,method="spearman")

-0.07878787878787878

In [ ]:
Q6. pop mean  = 400
      Sample mean = 370
      Sample std  = 30
      C.I  = 95%
      N = 80

In [66]:
s = np.random.normal(loc = 370 , scale = 30,size =80)
s

array([401.17707452, 352.39727306, 374.48212431, 332.51220844,
       331.63006649, 420.14266219, 367.06776192, 370.57626492,
       377.33929617, 359.20448867, 322.02767507, 346.24754708,
       336.74760759, 413.4334481 , 380.73067079, 413.12947581,
       391.69705385, 396.30929658, 349.47552669, 421.01593743,
       346.00911588, 392.70758957, 381.65628886, 373.99618357,
       299.28361184, 373.97921343, 415.50935026, 427.51177236,
       341.81694178, 426.15942136, 378.00702249, 300.7882545 ,
       365.54548304, 391.66707851, 397.07304348, 394.57891203,
       361.73322565, 345.67491719, 366.03060626, 312.9739235 ,
       405.19502383, 347.65232982, 365.88174407, 387.69477021,
       379.66005343, 371.39052087, 331.09899481, 364.06345507,
       393.87363873, 366.57513085, 375.32816066, 401.677556  ,
       407.63640215, 358.86250156, 331.8111538 , 361.64258763,
       274.22260274, 402.26836268, 396.15442381, 339.98007168,
       350.0405277 , 351.50539296, 342.12571254, 380.68

In [ ]:
Q7. pop mean  = 33
       Sample mean = 30
       Sample std = 2.5
      Alpha = 0.10
      N = 8

In [64]:
z = np.random.normal(loc = 30,scale = 2.5,size = 8)
z

array([28.76759215, 29.23045235, 29.06389647, 26.08674221, 29.90278581,
       25.83887708, 29.895316  , 25.12226834])

In [ ]:
Q8. 
Observed 
A
B
C
D
Owned 1 dog
60
50
30
20
Owned 2 dog
30
20
15
10

 Check for the degree of independence 



In [4]:
import pandas as pd
df = pd.DataFrame({'Owned 1 dog': [60, 50, 30, 20], 'Owned 2 dog' : [30, 20, 15, 10]}, index = ['A', "B", "c", "D"])

In [6]:
import scipy.stats as st

In [7]:
val = st.chi2_contingency(df)

In [8]:
val

(0.5128968253968255,
 0.9160490360646937,
 3,
 array([[61.27659574, 28.72340426],
        [47.65957447, 22.34042553],
        [30.63829787, 14.36170213],
        [20.42553191,  9.57446809]]))